Repository leo-daniel/strive, pull requests merged in 2018-08, with the labels that each got.

#2 Create PULL_REQUEST_TEMPLATE.md
  PULL_REQUEST_TEMPLATE.md
Labels: setup

#4 Add template for README.md
  README.md
Labels: setup

#3 ld-eslint
  .eslintrc.js
  LICENSE
  app/test.txt
  docs/test.txt
  package-lock.json
  package.json
  test/test.txt
Labels: setup

#5 Add Bootcamp 16-4-code setup
  config/config.json
  models/example.js
  models/index.js
  models/schema.sql
  package-lock.json
  package.json
  public/js/index.js
  public/styles/styles.css
  routes/apiRoutes.js
  routes/htmlRoutes.js
  server.js
  test/canary.test.js
  views/404.handlebars
  views/example.handlebars
  views/index.handlebars
  views/layouts/main.handlebars
Labels: setup

#24 Repo Setup Update
  .eslintrc.js
  LICENSE
  README.md
  app/test.txt
  config/config.json
  db/schema.sql
  docs/test.txt
  package-lock.json
  package.json
  views/layouts/main.handlebars
Labels: setup

#44 removed duplicate .env entry, removed package.json
  .gitignore
Labels: back-end, bug

#57 Update issue templates
  .github/ISSUE_TEMPLATE/feature_request.md
Labels: setup

#58 Update Bug Reports issue templates
  .github/ISSUE_TEMPLATE/bug_report.md
Labels: setup

#59 Feature sql
  db/schema.sql
Labels: bug

#61 Heroku Procfile added
  package-lock.json
  package.json
Labels: bug, heroku

#70 NPM updates with ESLint Standard & merge with Jordan updates
  package-lock.json
  package.json
Labels: setup

#73 Feature new task
  package-lock.json
  public/js/userInput.js
  public/styles/styles.css
  views/layouts/main.handlebars
  views/userInput.handlebars
Labels: BootStrap 4.0

#82 Add bulma-start node package. Removed .vscode-DIR with settings.json
  .vscode/settings.json
  package-lock.json
  package.json
Labels: npm-update

#103 Bulma setup
  .vscode/settings.json
  package-lock.json
  package.json
  public/js/index.js
  public/styles/bulma.css
  public/styles/sass/main.scss
  public/styles/styles.css
  views/calendar.handlebars
  views/index.handlebars
  views/layouts/main.handlebars
Labels: bulma, front-end

#104 Uncomment CSS in bulma.css. Remove calendar from index.handlebars.
  public/styles/bulma.css
  public/styles/styles.css
  views/calendar.handlebars
  views/index.handlebars
  views/layouts/main.handlebars
Labels: bug, bulma, front-end, handlebars

#139 bulma calendar commits
  package-lock.json
Labels: bulma, calendar
